const NavigationRoutes = {
    AUTH_STACK: {
        SPLASH: "SPLASH_SCREEN",
        LOGIN: "LOGIN_SCREEN",
        SIGN_UP: "SIGNUP_SCREEN",
        EMAIL_CONFIRMATION: "EMAIL_CONFIRMATION_SCREEN",
        OTP_VERIFICATION: "OTP_VERIFICATION_SCREEN",
        RESET_PASSWORD : "RESET_PASSWORD_SCREEN",
        NOTIFICATION: "NOTIFICATION_SCREEN",
       
    },
    APP_STACK: {
        HOME: "HOME_SCREEN",
        NOTIFICATION: "NOTIFICATION_SCREEN",
        CHAT_SCREENS: "CHAT_SCREENS",

    }
}

export default NavigationRoutes;